---
layout: post
title: Darkness at Noon
author: Gates
categories: [Literature]
tags: [Soviet-Union, Cold-War, Communism]
---
 This book, originally published in 1940, is about a loyal Bolshevik who finds himself the object of the party's ire. He understands how fickle the party can be but he has to confront the decision of keeping his loyalty to the party and lie about his actions or maintain his integrity and prevent the party from being to have the propaganda show trial it needs to create confidence for the people. The book is great at showing the cynicism of the Bolshevik party and how any compromise was necessary as long as it advanced the power of the party.

Rubashov was part of the revolutionary cadre of the Bolshevik party and he knows that the party is always right, even if it contradicts previous positions. Rubashov is also sure that the party will work for the betterment of mankind, even if individuals have to die in order for the party to succeed. Unfortunately for Rubashov, the events of the book will force him to confront in a very personal way his commitment to his ideals.

The book begins with the arrest of Rubashov. You do not have much prologue but the books uses a series of flashback while Rubashov is in prison to help you gain insight from his life before his arrest. Once in jail, Rubashov realizes that this will mean his death. The only thing open to question is whether or not he will die silently, executed in prison, a so-called administrative sentence. Or, will he go through a public trial in order to show the people the truth of the threat to the party that makes the repressive security state and the deprivations of daily life necessary. In order for the show trial to occur, Rubashov must confess to the crimes the party alleges he committed.

One of the more interesting aspects of the narrative is that you get to see previous times when Rubashov comes face to face with the cruelty of party but as an observer. His recollections of these times are instructive in how the reader gets to see him struggle with his actions in the past and determining how his previous failures should influence the decision set before him. You also get a sense of how the party works through the interrogators' actions when they are pressuring Rubashov to confess. He initially works with an old colleague of the party who wants to rely on the relationship that Rubashov and he share in order to extract the necessary information. However, there are other interrogators who push for a more aggressive approach in order to deliver a confession sooner. You get a great sense in this book about how invasive the party is in the lives of those who live under its control.  

Throughout the narrative, the reader gets to see the internal dialogue that Rubahsov goes through in order to work out his position about the contradictions of his beliefs. Knowing that death will come no matter his decision, he has to discern whether the higher purpose of his death will be to serve the party one last time or to stay true to himself and die a non-entity hoping for a far distant posthumous rehabilitation. 